// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9ngiZ7yoUwkp8AGBB1F2KBTVVxu-TxVg',
    appId: '1:308007931462:android:3ba3d250f991ef32988447',
    messagingSenderId: '308007931462',
    projectId: 'chat-app-adb3f',
    storageBucket: 'chat-app-adb3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhXhaqFxp2nTJTj2yhSEQ6bVjngjF65Gk',
    appId: '1:308007931462:ios:f0e51811db2a4b01988447',
    messagingSenderId: '308007931462',
    projectId: 'chat-app-adb3f',
    storageBucket: 'chat-app-adb3f.appspot.com',
    iosClientId: '308007931462-9mgeb71qm7d93ui1ak58u4sj7bjcetcp.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhXhaqFxp2nTJTj2yhSEQ6bVjngjF65Gk',
    appId: '1:308007931462:ios:f0e51811db2a4b01988447',
    messagingSenderId: '308007931462',
    projectId: 'chat-app-adb3f',
    storageBucket: 'chat-app-adb3f.appspot.com',
    iosClientId: '308007931462-9mgeb71qm7d93ui1ak58u4sj7bjcetcp.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
